### ISSUE TITLE
position the "open all", "close all", .... buttons absolutely on the right

### ISSUE THREAD

**Issue by kohlhase** [MathWebSearch/frontend#12]
I really like the absolute positioning of the formula preview on the right. It would be great to have the action buttons there too to have an "interation panel"  (I believe).

**Comment by typohnebild** [comment]
I have created such a sticky header bar that contains now all this buttons and the statistics stuff.
There is surely some room to improve the styling. Just as an first Idea
What do you think about it?

**Comment by kohlhase** [comment]
not very beautiful yet, but the functionality is good.
