### ISSUE TITLE
hover explanations

### ISSUE THREAD

**Issue by kohlhase** [MathWebSearch/frontend#15]
It would be good to have on-hover explanation for all the buttons and interface functionality to make the interface more explorable. 

I would be willing to contribute explanations.

**Comment by typohnebild** [comment]
Now there are some tooltips, they can be enabled/disabled with the checkbox
the text is at the moment not that usefull, to edit the explanation you can edit the tooltips.json in the config folder [here](/MathWebSearch/frontend/blob/master/src/config/tooltips.json)

**Comment by kohlhase** [comment]
I think we should always have tooltips, and get rid of the enable button.

**Comment by typohnebild** [comment]
But thinking of a user using it multiple times and already knows what happens when clicking on a button, may get easily annoyed by the tooltips. At least I am mostly thankful, when I can disable tooltips in interfaces that I use often.

**Comment by kohlhase** [comment]
but then the button  has to be much much smaller, and not so up in your face.

**Comment by typohnebild** [comment]
I moved it a bit to the right so it's not in the center of the users view
