### ISSUE TITLE
show more

### ISSUE THREAD

**Issue by kohlhase** [MathWebSearch/frontend#6]
this button does not seem to do anything. (or the stats are wrong see #2) . 
In the "another example" example I am promised 15, but only see 9 in the first screen and "show more" does not do anything. 
I think the button should also be above the results as well.

**Comment by typohnebild** [comment]
This should be solved, in cases when no more results to show, the show more buttons disappears now
15b364f6d2aea4ccceac51b97eec8b2c76ec8d5b
